# Generated by Django 5.1.7 on 2025-04-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vslt_app', '0002_csvdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
